language: python
sudo: false

install:
  - pip install tox

script:
  - tox -r

matrix:
    include:
      - python: 3.7
        env: TOXENV=style
        dist: xenial
        sudo: true

      - python: 3.7
        env: TOXENV=coverage
        dist: xenial
        sudo: true

      - python: 3.7
        env: TOXENV=py37
        dist: xenial
        sudo: true

      - env: TOXENV=py38
        python: 3.8
        dist: xenial
        sudo: true

      - python: 3.8
        env: TOXENV=docs
        dist: xenial
        sudo: true
